/*
 * This source file was generated by the Gradle 'init' task
 */
package kindai.example

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun appTest() {
        // 簡単なテスト
        assertTrue(true, "Basic test should pass")
    }
}
